import "./menu.js";
import "./slider.js";
// import "./pizza-card.js";
import "./counter.js";
import "./events.js";
import "./Cart/CartViewModel.js";
import "./Pizza-card/CardView.js";
import "./checkout.js";
import "./notify.js";
import "./video.js";
